<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Playing in - JAKARTA</name>
   <tag></tag>
   <elementGuidId>1ccc6e71-1315-460e-ac65-66a5cb0c265f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu_nav_bar']/ul[2]/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f45ed77-3baa-4248-b50e-ba1b0f58a827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>gui.list_city.php?sid=</value>
      <webElementGuid>950b414a-d5f5-433f-9b29-f5aff59c05b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_bar-animate</value>
      <webElementGuid>a0124f33-e192-4f25-b851-81c627a82212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Playing in - JAKARTA</value>
      <webElementGuid>35f2ae63-3be7-403a-ad8f-6e1fdce90e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_nav_bar&quot;)/ul[@class=&quot;nav navbar-nav navbar-left&quot;]/li[@class=&quot;nav_bar-animate&quot;]/a[@class=&quot;nav_bar-animate&quot;]</value>
      <webElementGuid>b382e760-a7bc-4c1d-9a8d-f2036e0cd939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu_nav_bar']/ul[2]/li[4]/a</value>
      <webElementGuid>b6a2f893-d6c1-4ec2-bc29-ecdbdb6304d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Playing in - JAKARTA')]</value>
      <webElementGuid>5257bb16-94a1-469d-852d-4e9c53297f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Playing in - JAKARTA']/parent::*</value>
      <webElementGuid>c1d5deb1-d8a6-4d20-8aa7-5951d9dc8b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'gui.list_city.php?sid=')]</value>
      <webElementGuid>7af0f238-730c-4d77-b2fd-9b6e7f896a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[4]/a</value>
      <webElementGuid>cb4912ea-176d-41ad-aa8b-cd73b2f93b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'gui.list_city.php?sid=' and (text() = 'Playing in - JAKARTA' or . = 'Playing in - JAKARTA')]</value>
      <webElementGuid>a863b2b2-4826-4aa4-adbf-ccc5106e4573</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
