<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EMPIRE XXI</name>
   <tag></tag>
   <elementGuidId>b4a31bc5-668f-489b-b246-c3ba83fec5ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='id'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4d5e0bd0-32c5-4000-a939-68f1556a52e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>a164fceb-a0bb-40f8-8457-7b74fe912be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='gui.schedule.php?sid=&amp;find_by=1&amp;cinema_id=YGYEMPR&amp;movie_id=';</value>
      <webElementGuid>3d9badd9-69ea-4189-b950-a1dd0c09b559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EMPIRE XXI</value>
      <webElementGuid>9e4ce24f-1a1e-4885-96ff-3b1762c6fa2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ini&quot;)/div[@class=&quot;all&quot;]/li[@class=&quot;list-group-item&quot;]/div[@id=&quot;id&quot;]</value>
      <webElementGuid>09be7f89-fece-4841-8f59-b6bc1898bed9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='id'])[5]</value>
      <webElementGuid>88ccddd2-e501-43a3-9b52-2fca92b633df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ini']/div[3]/li[2]/div</value>
      <webElementGuid>4f547c73-2af9-4891-8168-de1f96eecc14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JOGJA CITY PREMIERE'])[1]/following::div[3]</value>
      <webElementGuid>41f71dde-5a62-4cba-af94-998fc9f6d923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JOGJA CITY XXI'])[1]/preceding::div[1]</value>
      <webElementGuid>07d5f68a-0bab-4aa8-8ccd-b1635c81ed60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SLEMAN CITY HALL XXI'])[1]/preceding::div[2]</value>
      <webElementGuid>f918c9db-378e-46cd-ac37-268e73f2afb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EMPIRE XXI']/parent::*</value>
      <webElementGuid>64b24719-6f4e-4ae8-a2d8-34fc1d3d0e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/li[2]/div</value>
      <webElementGuid>4ad67a6e-24b8-4d7a-9d1f-227fb7a12883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'id' and (text() = 'EMPIRE XXI' or . = 'EMPIRE XXI')]</value>
      <webElementGuid>229d255a-3ae2-46fb-bca2-79d4305aa8d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
