<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_JOGJA CITY XXI</name>
   <tag></tag>
   <elementGuidId>2446ebd8-da82-4483-b403-9e4ec558fe89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='id'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>604f5ff8-d1cb-40f3-93b9-0228d2abdc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>5014731e-9f97-4576-b03c-8cfb14c995b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='gui.schedule.php?sid=&amp;find_by=1&amp;cinema_id=YGYJOCI&amp;movie_id=';</value>
      <webElementGuid>4bcc4e89-1d6a-4f0e-94e2-4ba68ebbd16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JOGJA CITY XXI</value>
      <webElementGuid>7dba7f35-31b6-4772-bf99-e65ea8e66121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ini&quot;)/div[@class=&quot;all&quot;]/li[@class=&quot;list-group-item&quot;]/div[@id=&quot;id&quot;]</value>
      <webElementGuid>cecb8924-ebcf-41ff-8d44-692ba886d792</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='id'])[6]</value>
      <webElementGuid>63b3a917-105c-48ad-a1e0-00578d4bfe41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ini']/div[3]/li[3]/div</value>
      <webElementGuid>e8767d3c-16ef-4d76-930f-d7967852a7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMPIRE XXI'])[1]/following::div[1]</value>
      <webElementGuid>97ce1f93-8d1d-4afb-b71a-ad8198daf7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SLEMAN CITY HALL XXI'])[1]/preceding::div[1]</value>
      <webElementGuid>bb5d36c6-9267-47f1-9293-06bddb7cf9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JOGJA CITY XXI']/parent::*</value>
      <webElementGuid>44372452-8f08-4c7b-bca9-57856941e29a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/li[3]/div</value>
      <webElementGuid>82e6e52b-bd4d-460f-88f3-b962dbda64d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'id' and (text() = 'JOGJA CITY XXI' or . = 'JOGJA CITY XXI')]</value>
      <webElementGuid>ac5b7aa1-4e82-4ec6-ba4b-9271208c41a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
