<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_YOGYAKARTA</name>
   <tag></tag>
   <elementGuidId>423ccb10-50f1-457d-9ff0-b722469a72a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick=&quot;location.href='gui.list_theater.php?sid=&amp;city_id=23';&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a263f8d0-faae-4f05-a445-9acc4da5692b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='gui.list_theater.php?sid=&amp;city_id=23';</value>
      <webElementGuid>83fb4af1-77d5-4bdd-b77a-7125a5edac4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YOGYAKARTA</value>
      <webElementGuid>8de0c9bc-170b-483d-b054-42456a581b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ini&quot;)/li[@class=&quot;list-group-item&quot;]/div[1]</value>
      <webElementGuid>cf26548a-51ac-43e4-9cea-def10c46e7e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;location.href='gui.list_theater.php?sid=&amp;city_id=23';&quot;]</value>
      <webElementGuid>e813de5c-3397-4070-a852-064cfa2489bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ini']/li[56]/div</value>
      <webElementGuid>5e86719f-993c-4018-906e-bb79c21369ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TERNATE'])[1]/following::div[1]</value>
      <webElementGuid>802ef619-cc12-4420-af0e-2f9e47ad8fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TASIKMALAYA'])[1]/following::div[2]</value>
      <webElementGuid>3d3c2d61-e43f-4bfc-b132-852836a99367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::div[3]</value>
      <webElementGuid>953e0795-5321-4fbf-84f3-f0e2625394e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='YOGYAKARTA']/parent::*</value>
      <webElementGuid>0987dcc7-6698-48b6-b40a-c41e72181f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[56]/div</value>
      <webElementGuid>7efbb25e-a9aa-48ab-b873-0ae2bb86576d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'YOGYAKARTA' or . = 'YOGYAKARTA')]</value>
      <webElementGuid>7374395b-56bc-470c-90cb-93d72eb78ef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
