<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_YOGYAKARTA</name>
   <tag></tag>
   <elementGuidId>71db7b3d-9ac8-4856-9e0f-84f1efb53b58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ini']/li[56]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>521d85d6-950f-4635-9bba-cea37b22933f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item</value>
      <webElementGuid>cb787ba5-aae5-4d50-a582-6727a8f93f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                     YOGYAKARTA                   </value>
      <webElementGuid>49442e0a-6226-4d79-a0a4-69a497534e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ini&quot;)/li[@class=&quot;list-group-item&quot;]</value>
      <webElementGuid>9ad9f68c-a34f-4837-a19c-84aae5482ba9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ini']/li[56]</value>
      <webElementGuid>9929642e-875b-473f-b023-e806d94f5887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TERNATE'])[1]/following::li[1]</value>
      <webElementGuid>a55d776a-41ae-42eb-b795-e703b0729228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TASIKMALAYA'])[1]/following::li[2]</value>
      <webElementGuid>5eba7ce4-96c5-426c-b34d-9eac894aab37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[56]</value>
      <webElementGuid>279ba128-b3da-41ff-b351-ff26256d41d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '                     YOGYAKARTA                   ' or . = '                     YOGYAKARTA                   ')]</value>
      <webElementGuid>2d624d44-6a39-4d11-92d3-287a853cee62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
