<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film Pope</name>
   <tag></tag>
   <elementGuidId>e8db4fb3-c878-4000-80a1-9883c8e75e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#23POPE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='23POPE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>99898c96-dd8c-498a-a310-37a2f840797a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>23POPE</value>
      <webElementGuid>49077934-7a39-4da9-935b-894b04c44e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/23POPE.jpg</value>
      <webElementGuid>0b5c5e96-3c31-45da-a953-7c053401ad82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;23POPE&quot;)</value>
      <webElementGuid>f7f9912c-65f6-498f-8898-7dc380c32a80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='23POPE']</value>
      <webElementGuid>43c9cc38-79fa-4fe5-9506-06ca9797442c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/23POPE.jpg')]</value>
      <webElementGuid>09163386-a3e3-4c94-9286-2c37d162c293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a/img</value>
      <webElementGuid>3d1e3296-9974-4ef1-84f5-4950d8dab82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '23POPE' and @src = 'https://web3.21cineplex.com/movie-images/23POPE.jpg']</value>
      <webElementGuid>31fca642-8d56-478b-aba8-f430a34c64b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
