<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film John Wick 4</name>
   <tag></tag>
   <elementGuidId>374ad749-965d-4169-8633-51029100a1ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#23JWC4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='23JWC4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a4e25c6a-afd7-4a70-a9a4-ddcf1cb67b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>23JWC4</value>
      <webElementGuid>fc109440-3f47-4821-9077-f79c91e1004c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/23JWC4.jpg</value>
      <webElementGuid>74115dbb-96b4-4035-9f5d-406b172a878f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;23JWC4&quot;)</value>
      <webElementGuid>d1c1a205-fd5c-4bd0-8c04-5298f51b06a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='23JWC4']</value>
      <webElementGuid>01c03665-93fa-4518-bacb-9c8b2b03ea54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/23JWC4.jpg')]</value>
      <webElementGuid>8081a8b0-9de8-4c8d-a825-7261cd32e0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/a/img</value>
      <webElementGuid>70ab3685-6c1f-4dbe-9cd4-93ebb56c3eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '23JWC4' and @src = 'https://web3.21cineplex.com/movie-images/23JWC4.jpg']</value>
      <webElementGuid>9f6ac431-bc68-42d4-b237-65d9bc0f6815</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
