<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film Super Mario</name>
   <tag></tag>
   <elementGuidId>318e5f87-b878-41f8-b930-65e69cbfbcfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#23SMX2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='23SMX2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>26e31d90-eca3-422a-8bbc-119d9b499beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>23SMX2</value>
      <webElementGuid>7bd94e5b-e695-46d6-afca-ee275e8af9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/23SMX2.jpg</value>
      <webElementGuid>0f59fd04-f388-43f3-83c7-10c63ea97db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;23SMX2&quot;)</value>
      <webElementGuid>e2c5c0bc-249a-44ad-8ea7-cb580c03b3bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='23SMX2']</value>
      <webElementGuid>b5a183bf-271b-4a65-a480-8602eca514ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/23SMX2.jpg')]</value>
      <webElementGuid>aaf973c8-d5a1-4347-930c-996b33acf223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/a/img</value>
      <webElementGuid>58219ef7-03ed-43e1-b258-7cb5621c4833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '23SMX2' and @src = 'https://web3.21cineplex.com/movie-images/23SMX2.jpg']</value>
      <webElementGuid>0c378120-78d9-45cf-9ca5-ca992ea02757</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
