<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film Ride On</name>
   <tag></tag>
   <elementGuidId>27f10524-fb7c-498f-bc23-9e07943e64d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#23RION</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='23RION']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5ec38876-787e-473a-a4ff-d9cc010ec55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>23RION</value>
      <webElementGuid>9b9f1d1d-cb71-4ccc-b565-814319173429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/23RION.jpg</value>
      <webElementGuid>4beaf27c-22b3-4410-b95a-eb6cd57f8446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;23RION&quot;)</value>
      <webElementGuid>f9210c58-dc47-4fef-91a5-d12d8bb33537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='23RION']</value>
      <webElementGuid>31ff2131-d575-48bd-9366-39ec5d6ef89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/23RION.jpg')]</value>
      <webElementGuid>a82bd768-b592-4094-9469-6d36d4f15e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>dc09bcf9-dc07-4588-9e6d-3b69425e1ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '23RION' and @src = 'https://web3.21cineplex.com/movie-images/23RION.jpg']</value>
      <webElementGuid>05d98d20-7256-4828-b97a-33bd8ff49ec4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
