<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film Kartu Pos Wini</name>
   <tag></tag>
   <elementGuidId>f0512247-b8e8-4230-8aba-ef85222756b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#11KPWI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='11KPWI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c5dfccb0-4011-4356-928c-c0724443e6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>11KPWI</value>
      <webElementGuid>d60601f7-108d-4cce-81cb-694c04bc9db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/11KPWI.jpg</value>
      <webElementGuid>4357aa37-f4bf-42a3-ad93-4174b455689b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;11KPWI&quot;)</value>
      <webElementGuid>2d114ad5-2f63-436b-9a40-ec5dd7da5b49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='11KPWI']</value>
      <webElementGuid>7d11f40d-1936-4943-9de9-ed3dd72e0c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/11KPWI.jpg')]</value>
      <webElementGuid>99c832a9-a8f2-4c70-a65b-c3d7f31a6683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/a/img</value>
      <webElementGuid>65e09240-f4a4-4a1d-b5c6-ba22df900e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '11KPWI' and @src = 'https://web3.21cineplex.com/movie-images/11KPWI.jpg']</value>
      <webElementGuid>97b7170d-696b-45b4-96c3-fff226003b25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
