<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film Buya Hamka</name>
   <tag></tag>
   <elementGuidId>a704c677-6be4-400f-ad5e-5e2f9d8eec01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#13BHAA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='13BHAA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6d2eaa5a-aad7-4c03-aeeb-b65ade739b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>13BHAA</value>
      <webElementGuid>e9dc9ff2-8f4f-4b4e-9070-77bee8206759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/13BHAA.jpg</value>
      <webElementGuid>c3c05c84-b7f6-455b-ba9c-c2e11e0e7873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;13BHAA&quot;)</value>
      <webElementGuid>afec8b3d-d73e-448b-990d-890dd6edd8c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='13BHAA']</value>
      <webElementGuid>e7d8ffdb-215e-4ccc-80c2-89d4e7c1d99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/13BHAA.jpg')]</value>
      <webElementGuid>4cfb05dc-606d-4a8a-b622-4ab57d7f946a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/img</value>
      <webElementGuid>1af5371c-923c-4be5-97f2-fc40e7354eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '13BHAA' and @src = 'https://web3.21cineplex.com/movie-images/13BHAA.jpg']</value>
      <webElementGuid>95862bc8-1bc9-4b25-a5bd-84836f1c98df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
