<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film Jin dan Jun</name>
   <tag></tag>
   <elementGuidId>a706dd79-3c30-482d-8df9-c48355cc1222</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#13JJUN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='13JJUN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d3cbd383-1437-4d3c-adae-ce6adb849b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>13JJUN</value>
      <webElementGuid>b6fd544e-0684-45b4-b177-aff536e1b2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/13JJUN.jpg</value>
      <webElementGuid>760fcedb-fffd-4a58-b32d-428da2c4e78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;13JJUN&quot;)</value>
      <webElementGuid>446ef85c-010f-4b5c-a4c9-77c88dac4caa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='13JJUN']</value>
      <webElementGuid>285a19a8-d44b-44dd-ba6d-50c63730d4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/13JJUN.jpg')]</value>
      <webElementGuid>88a3c63c-cb62-4524-9d23-52b6d01d37eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a/img</value>
      <webElementGuid>73f812a1-a3be-45ad-b766-671f78e050b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '13JJUN' and @src = 'https://web3.21cineplex.com/movie-images/13JJUN.jpg']</value>
      <webElementGuid>b1aadb37-b704-4aff-97b3-353dc5b13a11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
