<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film Guardian of Galaxy</name>
   <tag></tag>
   <elementGuidId>59364a39-b225-485a-9a75-1f0597f9d776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#23GOG3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='23GOG3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c990334d-8fe5-4647-9e64-5c32b76a6cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>23GOG3</value>
      <webElementGuid>2de2551c-e7e8-4433-bc35-c54fb9c1929c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/23GOG3.jpg</value>
      <webElementGuid>6e469cad-7b39-4685-94f9-aba63b51ea60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;23GOG3&quot;)</value>
      <webElementGuid>75de1ca2-bfec-43c2-aef5-11b2d563200d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='23GOG3']</value>
      <webElementGuid>02729892-9297-4d65-8aa1-f991222cc988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/23GOG3.jpg')]</value>
      <webElementGuid>b99a819c-7c71-4756-963e-42b98831faa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/img</value>
      <webElementGuid>4295d3da-ba9b-47e3-82f6-54f364910fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '23GOG3' and @src = 'https://web3.21cineplex.com/movie-images/23GOG3.jpg']</value>
      <webElementGuid>88573eb9-786c-4d59-8273-c6aed94ba8bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
