<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film Yokaipedia</name>
   <tag></tag>
   <elementGuidId>7e9fef9d-5180-4850-8582-c5d87618261e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22YOKA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='22YOKA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0bede543-a79d-4b06-b800-6aa46af8b715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22YOKA</value>
      <webElementGuid>72a2c1b8-6fea-492c-9084-d8c4a134914e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/22YOKA.jpg</value>
      <webElementGuid>8df198c3-d7e1-4a33-963e-3e08df71eee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22YOKA&quot;)</value>
      <webElementGuid>8e9a0ef5-ce38-4d47-a5a9-251054cb8ffd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='22YOKA']</value>
      <webElementGuid>dffc9c6b-53bc-4fa1-9ce7-17b05b64c26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/22YOKA.jpg')]</value>
      <webElementGuid>47c92858-d5aa-45f7-892e-9def15f9dae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/a/img</value>
      <webElementGuid>c39c6238-7c05-4a2a-a2db-ce6499037c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '22YOKA' and @src = 'https://web3.21cineplex.com/movie-images/22YOKA.jpg']</value>
      <webElementGuid>8e856198-1ee6-49ce-b90e-23bec3938aa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
