<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film Covenant</name>
   <tag></tag>
   <elementGuidId>5c060755-0d7f-404d-833d-dc83a1d5ba4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#23GRTC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='23GRTC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>667f46e3-75bd-482a-ae15-f280364cb14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>23GRTC</value>
      <webElementGuid>949a85b9-0f2f-491c-8096-64488ca13132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/23GRTC.jpg</value>
      <webElementGuid>0ebb4790-2af4-4e75-be98-c6c90e867818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;23GRTC&quot;)</value>
      <webElementGuid>91b6936c-455e-4ef0-a42e-9c1eb9d8d81d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='23GRTC']</value>
      <webElementGuid>cba50acb-6eb0-42e1-b78f-2364077437ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/23GRTC.jpg')]</value>
      <webElementGuid>ca303e4d-521c-42ca-a7e1-bbdc12f66f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a/img</value>
      <webElementGuid>714b03dc-9aa0-419c-b912-0eae87900d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '23GRTC' and @src = 'https://web3.21cineplex.com/movie-images/23GRTC.jpg']</value>
      <webElementGuid>194b73c8-0ec0-413f-87a4-00a65b5a7265</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
