<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>film65</name>
   <tag></tag>
   <elementGuidId>29c5e0a1-68da-4196-a5a3-56896e980d7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#2365XX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='2365XX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6745bd38-4ca4-416e-a33c-dbbd2080e09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2365XX</value>
      <webElementGuid>73ebc574-b5ae-42ff-bc75-48c53b9ea609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/2365XX.jpg</value>
      <webElementGuid>c7f87650-3920-40e5-9803-23beb190c0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2365XX&quot;)</value>
      <webElementGuid>faac295b-7887-4c79-ac33-b86e55bfe87d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='2365XX']</value>
      <webElementGuid>c7215eba-0e3b-4e20-8156-8e2688e6a5c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/2365XX.jpg')]</value>
      <webElementGuid>09aa6af3-db9c-412f-9763-ac7467332042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>0d7af482-3797-48e6-a16c-e2e9b78135e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '2365XX' and @src = 'https://web3.21cineplex.com/movie-images/2365XX.jpg']</value>
      <webElementGuid>435f80f2-eb8f-49d9-b073-552e318cce59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
