<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film Dedemit</name>
   <tag></tag>
   <elementGuidId>10252186-ec13-48a1-b6e6-7e41cbf93f7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#13DDMH</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='13DDMH']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2ea30760-0b93-4bbc-9e7b-9cf1330f9450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>13DDMH</value>
      <webElementGuid>3fd832d3-9913-4bbb-a790-2e54e11568f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/13DDMH.jpg</value>
      <webElementGuid>161cb9ba-7c1d-4732-881a-ea23db73530a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;13DDMH&quot;)</value>
      <webElementGuid>4198429b-2a72-42b1-a2f5-44c2ce45e093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='13DDMH']</value>
      <webElementGuid>97344bdd-034f-4cd3-9fbb-41d719a6cdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/13DDMH.jpg')]</value>
      <webElementGuid>3aec2dc0-af49-4ab5-861e-dafbeeecbb56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>7d772292-09be-4742-8e14-62413d2b39d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '13DDMH' and @src = 'https://web3.21cineplex.com/movie-images/13DDMH.jpg']</value>
      <webElementGuid>d3fbe669-1881-4336-afcd-1f1a86d091f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
