<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film Guradian of falaxy IMAX</name>
   <tag></tag>
   <elementGuidId>8a54a70c-d958-46fc-a4e9-856d1d516d75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#23G3X2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='23G3X2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>abff888f-01f5-4ac7-bdd4-9d78fb3944db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>23G3X2</value>
      <webElementGuid>53e7a673-fea5-4c95-9d48-06a190cf998c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/23G3X2.jpg</value>
      <webElementGuid>28debf9f-ba5e-4e8e-b550-53c0b1d7506e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;23G3X2&quot;)</value>
      <webElementGuid>b07eba2c-c2da-4eb9-af71-8db093e2e318</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='23G3X2']</value>
      <webElementGuid>34bea56f-9c1d-4851-a1af-dcf7fd85ffeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/23G3X2.jpg')]</value>
      <webElementGuid>15627988-e330-4332-bb92-e67d37f0dda8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/img</value>
      <webElementGuid>507e76b6-2179-4a4e-a50e-cdd60ba5523e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '23G3X2' and @src = 'https://web3.21cineplex.com/movie-images/23G3X2.jpg']</value>
      <webElementGuid>ecf31a5c-67e3-454d-ba5d-b1f67ac67543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
