<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Film asterix</name>
   <tag></tag>
   <elementGuidId>87cb8ae2-0112-4813-8a48-656d72ebf58c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#23AOMK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='23AOMK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8cb2492d-c238-48c8-976c-2a6a77be9e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>23AOMK</value>
      <webElementGuid>8b346eb6-2092-4185-8c1c-a9dd935ba142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/23AOMK.jpg</value>
      <webElementGuid>5c55f00d-f2fc-46fe-af3d-71710a3989a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;23AOMK&quot;)</value>
      <webElementGuid>23dec6db-22a8-4f72-aeca-75f1f148d47a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='23AOMK']</value>
      <webElementGuid>ab57111f-6bc0-4520-b065-48801b2d2f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/23AOMK.jpg')]</value>
      <webElementGuid>7f4867b3-4894-4b7f-8300-96f673c7059b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>f7bf4cbf-a2d2-46e9-a33a-d808497492c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '23AOMK' and @src = 'https://web3.21cineplex.com/movie-images/23AOMK.jpg']</value>
      <webElementGuid>b5ed3faa-b2a3-4c2c-ac3f-6ffde04305c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
